# Generated by Django 3.0 on 2020-04-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topologies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topology', models.CharField(max_length=50)),
                ('component', models.CharField(max_length=30)),
                ('latency', models.FloatField()),
                ('capacity', models.FloatField()),
            ],
        ),
    ]
