# Generated by Django 3.0 on 2020-04-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topologies',
            name='component',
            field=models.CharField(max_length=50),
        ),
    ]
